Sr experience
iTwin/synchronization-report-react pull request #81
Opened 2023-08-08 14:38 UTC by nimam-bentley

https://bentleycs.visualstudio.com/beconnect/_workitems/edit/1244144

report issue modal adjusted to match that in PBI 1244144 and latest InstantOn update

2023-08-08 15:49 UTC, nimam-bentley commented
<img width="1008" alt="Screen Shot 2023-08-08 at 11 48 27 AM" src="https://github.com/iTwin/synchronization-report-react/assets/100853841/c7082847-29f4-47d0-9bfa-9387b7105d0f">

2023-08-17 13:59 UTC, Aidas-Vaiksnoras requested changes

2023-08-17 14:50 UTC, nimam-bentley commented on src/components/ReportDebugIds.tsx
> +    ${displayStrings.jobRunID}: ${debugIds['Job Run Id']}
<img width="532" alt="Screen Shot 2023-08-17 at 10 50 43 AM" src="https://github.com/iTwin/synchronization-report-react/assets/100853841/8f431d71-d9d2-449d-b980-4b9397f7b719">

2023-08-17 14:55 UTC, nimam-bentley commented on src/components/ReportDebugIds.tsx
> +    ${displayStrings.jobRunID}: ${debugIds['Job Run Id']}
<img width="510" alt="Screen Shot 2023-08-17 at 10 55 31 AM" src="https://github.com/iTwin/synchronization-report-react/assets/100853841/97c67346-fff3-4e51-9c3f-20d4367ed189">

2023-08-18 05:18 UTC, Aidas-Vaiksnoras approved these changes

2023-08-18 13:15 UTC, merged